# -*- coding: utf-8 -*-
"""Placement PackageTracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18se6HktIgqtGBUazI89cbR_Weh46UtfY
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv('placement.csv')
df.head()

df.isnull().sum()

df.info()

X = df['cgpa'].values.reshape(-1, 1)
y = df['package'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
r2 = r2_score(y_test, y_pred)
print(f"R-squared value: {r2}")

plt.scatter(X_test, y_test, color='blue')
plt.plot(X_test, y_pred, color='red')
plt.title('CGPA vs Placement Package')
plt.xlabel('CGPA')
plt.ylabel('Placement Package')
plt.show()

def predict_package(cgpa):
    cgpa = np.array(cgpa).reshape(-1, 1)
    predicted_package = model.predict(cgpa)
    return predicted_package[0]
cgpa_input = float(input("Enter CGPA: "))
predicted_package = predict_package(cgpa_input)
print(f"The predicted placement package for CGPA {cgpa_input} is: {predicted_package} LPA")